// src/views/auth/Register.vue
<script setup lang="ts">
import RegisterForm from '../../components/auth/RegisterForm.vue'

// Set document title
if (typeof document !== 'undefined') {
  document.title = 'Registro - Toiter'
}
</script>

<template>
  <div class="container">
    <h1 class="title">Toiter</h1>
    <p class="subtitle">Crie sua conta</p>
    <RegisterForm />
    <p class="redirect">
      Já tem uma conta? <router-link to="/auth/login">Faça login</router-link>
    </p>
  </div>
</template>

<style scoped>
.container {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  min-height: 100vh;
  background-color: var(--color-background);
  animation: fadeIn 0.5s;
}

.title {
  color: var(--color-primary);
  font-size: var(--font-size-large);
  margin-bottom: 16px;
}

.subtitle {
  margin-bottom: 20px;
  color: var(--color-text);
  font-size: var(--font-size-regular);
}

.redirect {
  margin-top: 20px;
  color: var(--color-text);
}

.redirect a {
  color: var(--color-primary);
  text-decoration: none;
  font-weight: bold;
}

.redirect a:hover {
  text-decoration: underline;
}

@keyframes fadeIn {
  from {
    opacity: 0;
  }
  to {
    opacity: 1;
  }
}
</style>

// src/pages/auth/register.tsx
import React from 'react';
import styled from 'styled-components';
import RegisterForm from '../../components/auth/RegisterForm';

const RegisterPage = () => {
    return (
        <Container>
            <Title>Toiter</Title>
            <Subtitle>Crie sua conta</Subtitle>
            <RegisterForm />
            <Redirect>
                Já tem uma conta? <a href="/auth/login">Faça login</a>
            </Redirect>
        </Container>
    );
};

export default RegisterPage;

const Container = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  height: 100vh;
  background-color: ${({ theme }) => theme.colors.background};
`;

const Title = styled.h1`
  color: ${({ theme }) => theme.colors.primary};
  font-size: ${({ theme }) => theme.fontSizes.large};
  margin-bottom: 16px;
`;

const Subtitle = styled.p`
  margin-bottom: 20px;
  color: ${({ theme }) => theme.colors.text};
  font-size: ${({ theme }) => theme.fontSizes.regular};
`;

const Redirect = styled.p`
  margin-top: 20px;
  color: ${({ theme }) => theme.colors.text};
  a {
    color: ${({ theme }) => theme.colors.primary};
    text-decoration: none;
    font-weight: bold;
  }
`;
