// src/views/Chat.vue
<script setup lang="ts">
import {onMounted, onUnmounted, ref, computed} from 'vue'
import {type ChatPreview, chatService, type Message} from '../services/chatService'
import {useWebSocket} from '../composables/useWebSocket'
import {useAuthStore} from '../stores/auth'
import ChatList from '../components/ChatList.vue'
import ChatWindow from '../components/ChatWindow.vue'

const authStore = useAuthStore()
const { connect, disconnect, sendMessage: wsSendMessage, subscribeToMessages } = useWebSocket()

const chats = ref<ChatPreview[]>([])
const messages = ref<Message[]>([])
const selectedChatId = ref<number | null>(null)
const receiverUsername = ref<string>('')

const syncedChats = ref<Record<number, number>>({})
const isMobile = ref(false)

const loadChats = async () => {
  try {
    const response = await chatService.getMyChats()
    chats.value = response.content
  } catch (error) {
    console.error('Failed to load chats:', error)
  }
}

const selectChat = async (chatId: number) => {
  selectedChatId.value = chatId
  const chat = chats.value.find(c => c.chatId === chatId)
  if (chat) {
    receiverUsername.value = chat.receiverUsername
    await loadMessages(chatId)
  }
}

const loadMessages = async (chatId: number) => {
  try {
    const now = Date.now()
    const lastSynced = syncedChats.value[chatId] || 0
    const needsSync = now - lastSynced > 5 * 60 * 1000 // 5 minutes

    if (needsSync) {
      console.log(`Syncing messages for chat ${chatId} (last synced ${lastSynced ? new Date(lastSynced).toLocaleTimeString() : 'never'})`)
      messages.value = await chatService.syncChatMessages(chatId)
      syncedChats.value[chatId] = now
    } else {
      console.log(`Using cached messages for chat ${chatId}`)
      const storedMessagesStr = localStorage.getItem(`chat_${chatId}_messages`)
      if (storedMessagesStr) {
        messages.value = JSON.parse(storedMessagesStr)
      }
    }
  } catch (error) {
    console.error('Failed to sync messages:', error)
  }
}

const sendMessage = async (chatId: number, message: string) => {
  try {
    wsSendMessage(chatId, message)
    // Optimistically add the message
    const newMsg: Message = {
      id: Date.now(), // Temporary ID
      chatId,
      message,
      sender: authStore.user?.username || '',
      timestamp: new Date().toISOString()
    }
    messages.value.push(newMsg)
  } catch (error) {
    console.error('Failed to send message:', error)
  }
}

const startChat = async (username: string) => {
  try {
    const chatId = await chatService.startChat(username)
    await loadChats() // Reload chats to include the new one
    selectChat(chatId)
  } catch (error) {
    console.error('Failed to start chat:', error)
  }
}

const updateChats = (newChats: ChatPreview[]) => {
  chats.value = newChats
}

const backToList = () => {
  selectedChatId.value = null
  receiverUsername.value = ''
}

const handleResize = () => {
  isMobile.value = window.innerWidth <= 768
}

const receiverImageUrl = computed(() => {
  const chat = chats.value.find(c => c.chatId === selectedChatId.value)
  return chat?.receiverProfileImageUrl ?? null
})

onMounted(async () => {
  if (typeof document !== 'undefined') {
    document.title = 'Chat - Toiter'
  }

  await loadChats()

  if (authStore.user) {
    const token = localStorage.getItem('accessToken')
    if (token) {
      connect(token)
      subscribeToMessages((message: Message) => {
        if (message.chatId === selectedChatId.value) {
          messages.value.push(message)
          localStorage.setItem(`chat_${selectedChatId.value}_messages`, JSON.stringify(messages.value))
        }
        // Update last message in chats
        const chat = chats.value.find(c => c.chatId === message.chatId)
        if (chat) {
          chat.lastMessageContent = message.message
          chat.lastMessageSentDate = message.timestamp
          chat.lastMessageSender = message.sender
        }
      })
    }
  }

  handleResize()
  window.addEventListener('resize', handleResize)
})

onUnmounted(() => {
  disconnect()
  window.removeEventListener('resize', handleResize)
})
</script>

<template>
  <div class="container">
    <div class="chat-layout">
      <template v-if="isMobile">
        <ChatWindow
          v-if="selectedChatId"
          :selectedChatId="selectedChatId"
          :messages="messages"
          :receiverUsername="receiverUsername"
          :receiverImageUrl="receiverImageUrl"
          @sendMessage="sendMessage"
          @back="backToList"
        />
        <ChatList
          v-else
          :selectedChatId="selectedChatId"
          :chats="chats"
          @selectChat="selectChat"
          @startChat="startChat"
          @updateChats="updateChats"
        />
      </template>
      <template v-else>
        <ChatList
          :selectedChatId="selectedChatId"
          :chats="chats"
          @selectChat="selectChat"
          @startChat="startChat"
          @updateChats="updateChats"
        />
        <ChatWindow
          :selectedChatId="selectedChatId"
          :messages="messages"
          :receiverUsername="receiverUsername"
          :receiverImageUrl="receiverImageUrl"
          @sendMessage="sendMessage"
          @back="backToList"
        />
      </template>
    </div>
  </div>
</template>

<style scoped>
.container {
  display: flex;
  flex-direction: column;
  background-color: var(--color-background);
  height: calc(100vh - 80px);
  overflow: hidden;
}

.chat-layout {
  display: flex;
  flex: 1;
  background: var(--color-background-elevated);
  overflow: hidden;
}
</style>

// src/pages/chat.tsx
import styled from 'styled-components';
import dynamic from 'next/dynamic';
import Head from 'next/head';
import withAuth from '@/hoc/withAuth';
import { WebSocketProvider, useWebSocket } from '@/context/WebSocketContext';
import { chatService, ChatPreview, Message } from '@/services/chatService';
import React, { useEffect, useState, useCallback } from 'react';

const ChatListComponent = dynamic(() => import('@/components/chatList'), { ssr: false });
const ChatWindowComponent = dynamic(() => import('@/components/chatWindow'), { ssr: false });

const ChatContainer = styled.div`
    display: flex;
    height: 100%;
    max-height: 85vh;
    background: #fff;
    @media (max-width: 768px) {
        display: block;
    }
`;

const ChatPageContainer = styled.div`
    width: 100%;
    height: 100%;
    margin: 0;
    padding: 0;
    display: flex;
    flex-direction: column;
`;

const ChatPageContent: React.FC = () => {
    const { sendMessage, subscribeToMessages } = useWebSocket();
    const [chats, setChats] = useState<ChatPreview[]>([]);
    const [selectedChatId, setSelectedChatId] = useState<number | null>(null);
    const [messages, setMessages] = useState<Message[]>([]);
    const [syncedChats, setSyncedChats] = useState<Record<number, number>>({});
    const [isMobile, setIsMobile] = useState(false);

    useEffect(() => {
        const handleResize = () => {
            setIsMobile(window.innerWidth <= 768);
        };
        handleResize();
        window.addEventListener('resize', handleResize);
        return () => window.removeEventListener('resize', handleResize);
    }, []);

    const loadMessages = useCallback(async (chatId: number) => {
        try {
            const now = Date.now();
            const lastSynced = syncedChats[chatId] || 0;
            const needsSync = now - lastSynced > 5 * 60 * 1000; // 5 minutes

            if (needsSync) {
                console.log(`Syncing messages for chat ${chatId} (last synced ${lastSynced ? new Date(lastSynced).toLocaleTimeString() : 'never'})`);
                const syncedMessages = await chatService.syncChatMessages(chatId);
                setMessages(syncedMessages);
                setSyncedChats(prev => ({ ...prev, [chatId]: now }));
            } else {
                console.log(`Using cached messages for chat ${chatId}`);
                const storedMessagesStr = localStorage.getItem(`chat_${chatId}_messages`);
                if (storedMessagesStr) {
                    setMessages(JSON.parse(storedMessagesStr));
                }
            }
        } catch (error) {
            console.error('Failed to sync messages:', error);
        }
    }, [syncedChats]);

    const updateChatPreview = useCallback((message: Message) => {
        setChats(prevChats =>
            prevChats.map(chat =>
                chat.chatId === message.chatId
                    ? {
                        ...chat,
                        lastMessageContent: message.message,
                        lastMessageSender: message.sender,
                        lastMessageSentDate: message.timestamp,
                    }
                    : chat
            )
        );
    }, []);

    useEffect(() => {
        const unsubscribe = subscribeToMessages((message: Message) => {
            if (message.chatId === selectedChatId) {
                setMessages(prev => {
                    const updated = [...prev, message];
                    localStorage.setItem(`chat_${selectedChatId}_messages`, JSON.stringify(updated));
                    return updated;
                });
            }
            updateChatPreview(message);
        });

        return () => unsubscribe();
    }, [selectedChatId, updateChatPreview, subscribeToMessages]);

    useEffect(() => {
        if (selectedChatId) {
            loadMessages(selectedChatId);
        }
    }, [selectedChatId, loadMessages]);

    const handleStartChat = async (username: string) => {
        try {
            const chatId = await chatService.startChat(username);
            setSelectedChatId(chatId);
            const response = await chatService.getMyChats();
            setChats(response.content);
        } catch (error) {
            console.error('Failed to start chat:', error);
        }
    };

    return (
        <ChatContainer>
            {isMobile ? (
                selectedChatId ? (
                    <ChatWindowComponent
                        selectedChatId={selectedChatId}
                        messages={messages}
                        setMessages={setMessages}
                        sendMessage={sendMessage}
                        onBack={() => setSelectedChatId(null)}
                        receiverUsername={chats.find(chat => chat.chatId === selectedChatId)?.receiverUsername}
                    />
                ) : (
                    <ChatListComponent
                        selectedChatId={selectedChatId}
                        onSelectChat={setSelectedChatId}
                        onStartChat={handleStartChat}
                        chats={chats}
                        setChats={setChats}
                    />
                )
            ) : (
                <>
                    <ChatListComponent
                        selectedChatId={selectedChatId}
                        onSelectChat={setSelectedChatId}
                        onStartChat={handleStartChat}
                        chats={chats}
                        setChats={setChats}
                    />
                    <ChatWindowComponent
                        selectedChatId={selectedChatId}
                        messages={messages}
                        setMessages={setMessages}
                        sendMessage={sendMessage}
                        onBack={() => setSelectedChatId(null)}
                        receiverUsername={chats.find(chat => chat.chatId === selectedChatId)?.receiverUsername}
                    />
                </>
            )}
        </ChatContainer>
    );
};

const ChatPage = () => {
    return (
        <>
            <Head>
                <title>Messages | Toiter</title>
            </Head>
            <ChatPageContainer>
                <WebSocketProvider>
                    <ChatPageContent />
                </WebSocketProvider>
            </ChatPageContainer>
        </>
    );
};

export default withAuth(ChatPage);
