// src/views/Chat.vue
<script setup lang="ts">
import {onMounted, onUnmounted, ref} from 'vue'
import {useRouter} from 'vue-router'
import {type ChatPreview, chatService, type Message} from '../services/chatService'
import {useWebSocket} from '../composables/useWebSocket'
import {useAuthStore} from '../stores/auth'
import ChatList from '../components/ChatList.vue'
import ChatWindow from '../components/ChatWindow.vue'

const router = useRouter()
const authStore = useAuthStore()
const { connect, disconnect, sendMessage: wsSendMessage, subscribeToMessages } = useWebSocket()

const chats = ref<ChatPreview[]>([])
const messages = ref<Message[]>([])
const selectedChatId = ref<number | null>(null)
const receiverUsername = ref<string>('')

const syncedChats = ref<Record<number, number>>({})
const isMobile = ref(false)

const handleBack = () => {
  router.push('/feed')
}

const loadChats = async () => {
  try {
    const response = await chatService.getMyChats()
    chats.value = response.content
  } catch (error) {
    console.error('Failed to load chats:', error)
  }
}

const selectChat = async (chatId: number) => {
  selectedChatId.value = chatId
  const chat = chats.value.find(c => c.chatId === chatId)
  if (chat) {
    receiverUsername.value = chat.receiverUsername
    await loadMessages(chatId)
  }
}

const loadMessages = async (chatId: number) => {
  try {
    const now = Date.now()
    const lastSynced = syncedChats.value[chatId] || 0
    const needsSync = now - lastSynced > 5 * 60 * 1000 // 5 minutes

    if (needsSync) {
      console.log(`Syncing messages for chat ${chatId} (last synced ${lastSynced ? new Date(lastSynced).toLocaleTimeString() : 'never'})`)
      messages.value = await chatService.syncChatMessages(chatId)
      syncedChats.value[chatId] = now
    } else {
      console.log(`Using cached messages for chat ${chatId}`)
      const storedMessagesStr = localStorage.getItem(`chat_${chatId}_messages`)
      if (storedMessagesStr) {
        messages.value = JSON.parse(storedMessagesStr)
      }
    }
  } catch (error) {
    console.error('Failed to sync messages:', error)
  }
}

const sendMessage = async (chatId: number, message: string) => {
  try {
    wsSendMessage(chatId, message)
    // Optimistically add the message
    const newMsg: Message = {
      id: Date.now(), // Temporary ID
      chatId,
      message,
      sender: authStore.user?.username || '',
      timestamp: new Date().toISOString()
    }
    messages.value.push(newMsg)
  } catch (error) {
    console.error('Failed to send message:', error)
  }
}

const startChat = async (username: string) => {
  try {
    const chatId = await chatService.startChat(username)
    await loadChats() // Reload chats to include the new one
    selectChat(chatId)
  } catch (error) {
    console.error('Failed to start chat:', error)
  }
}

const updateChats = (newChats: ChatPreview[]) => {
  chats.value = newChats
}

const backToList = () => {
  selectedChatId.value = null
  receiverUsername.value = ''
}

const handleResize = () => {
  isMobile.value = window.innerWidth <= 768
}

onMounted(async () => {
  if (typeof document !== 'undefined') {
    document.title = 'Chat - Toiter'
  }

  await loadChats()

  if (authStore.user) {
    const token = localStorage.getItem('accessToken')
    if (token) {
      connect(token)
      subscribeToMessages((message: Message) => {
        if (message.chatId === selectedChatId.value) {
          messages.value.push(message)
          localStorage.setItem(`chat_${selectedChatId.value}_messages`, JSON.stringify(messages.value))
        }
        // Update last message in chats
        const chat = chats.value.find(c => c.chatId === message.chatId)
        if (chat) {
          chat.lastMessageContent = message.message
          chat.lastMessageSentDate = message.timestamp
          chat.lastMessageSender = message.sender
        }
      })
    }
  }

  handleResize()
  window.addEventListener('resize', handleResize)
})

onUnmounted(() => {
  disconnect()
  window.removeEventListener('resize', handleResize)
})
</script>

<template>
  <div class="container">
    <div class="chat-layout">
      <template v-if="isMobile">
        <ChatWindow
          v-if="selectedChatId"
          :selectedChatId="selectedChatId"
          :messages="messages"
          :receiverUsername="receiverUsername"
          @sendMessage="sendMessage"
          @back="backToList"
        />
        <ChatList
          v-else
          :selectedChatId="selectedChatId"
          :chats="chats"
          @selectChat="selectChat"
          @startChat="startChat"
          @updateChats="updateChats"
        />
      </template>
      <template v-else>
        <ChatList
          :selectedChatId="selectedChatId"
          :chats="chats"
          @selectChat="selectChat"
          @startChat="startChat"
          @updateChats="updateChats"
        />
        <ChatWindow
          :selectedChatId="selectedChatId"
          :messages="messages"
          :receiverUsername="receiverUsername"
          @sendMessage="sendMessage"
          @back="backToList"
        />
      </template>
    </div>
    <button class="back-button" @click="handleBack">
      ← Voltar para Feed
    </button>
  </div>
</template>

<style scoped>
.container {
  display: flex;
  flex-direction: column;
  background-color: var(--color-background);
  min-height: 100vh;
}

.chat-layout {
  display: flex;
  flex: 1;
  height: calc(100vh - 60px); /* Adjust for back button */
  background: var(--color-background-elevated);
  overflow: hidden;
}

.back-button {
  background: none;
  border: none;
  color: var(--color-primary);
  cursor: pointer;
  font-size: var(--font-size-regular);
  padding: 16px;
  align-self: flex-start;
}

.back-button:hover {
  text-decoration: underline;
}
</style>

// src/components/chat.tsx
import React, { useEffect, useState, useCallback, useRef } from 'react';
import styled from 'styled-components';
import { chatService, ChatPreview, Message } from '@/services/chatService';
import NewChat from './newChat';
import { useAuth } from "@/context/AuthContext";
import { useWebSocket } from '@/context/WebSocketContext';

const ChatContainer = styled.div`
  display: flex;
  height: calc(100vh - 60px);
  background: white;
  border-radius: 8px;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
  overflow: hidden;
`;

const Sidebar = styled.div`
  width: 320px;
  border-right: 1px solid #eee;
  display: flex;
  flex-direction: column;
`;

const ChatList = styled.div`
  flex: 1;
  overflow-y: auto;
`;

const ChatItem = styled.div<{ active: boolean }>`
  padding: 15px;
  border-bottom: 1px solid #eee;
  cursor: pointer;
  background: ${props => props.active ? '#f0f2f5' : 'transparent'};

  &:hover {
    background: #f0f2f5;
  }
`;

const ChatWindow = styled.div`
  flex: 1;
  display: flex;
  flex-direction: column;
`;

const MessageList = styled.div`
  flex: 1;
  overflow-y: auto;
  padding: 20px;
  display: flex;
  flex-direction: column;
  gap: 10px;
`;

const MessageBubble = styled.div<{ isMine: boolean }>`
  max-width: 70%;
  padding: 10px 15px;
  border-radius: 16px;
  background: ${props => props.isMine ? '#0084ff' : '#4CAF50'};
  color: ${props => props.isMine ? 'white' : 'black'};
  align-self: ${props => props.isMine ? 'flex-end' : 'flex-start'};
`;

const InputArea = styled.div`
  padding: 20px;
  border-top: 1px solid #eee;
  display: flex;
  gap: 10px;
`;

const Input = styled.input`
  flex: 1;
  padding: 10px;
  border: 1px solid #eee;
  border-radius: 20px;
  outline: none;

  &:focus {
    border-color: #0084ff;
  }
`;

const SendButton = styled.button`
  padding: 10px 20px;
  border-radius: 20px;
  background: #0084ff;
  color: white;
  border: none;
  cursor: pointer;

  &:hover {
    background: #0073e6;
  }
`;

const Chat: React.FC = () => {
  const { user } = useAuth();
  const { sendMessage, subscribeToMessages } = useWebSocket();
  const [chats, setChats] = useState<ChatPreview[]>([]);
  const [selectedChatId, setSelectedChatId] = useState<number | null>(null);
  const [messages, setMessages] = useState<Message[]>([]);
  const [newMessage, setNewMessage] = useState('');
  const [syncedChats, setSyncedChats] = useState<Record<number, number>>({});
  const messagesEndRef = useRef<HTMLDivElement>(null);

  const loadChats = useCallback(async () => {
    console.log('📬 Loading chats...');
    try {
      const response = await chatService.getMyChats();
      setChats(response.content);
    } catch (error) {
      console.error('Failed to load chats:', error);
    }
  }, []);

  const loadMessages = useCallback(async (chatId: number) => {
    try {
      const now = Date.now();
      const lastSynced = syncedChats[chatId] || 0;
      const needsSync = now - lastSynced > 5 * 60 * 1000; // 5 minutes

      if (needsSync) {
        console.log(`Syncing messages for chat ${chatId} (last synced ${lastSynced ? new Date(lastSynced).toLocaleTimeString() : 'never'})`);
        const syncedMessages = await chatService.syncChatMessages(chatId);
        setMessages(syncedMessages);
        setSyncedChats(prev => ({ ...prev, [chatId]: now }));
      } else {
        console.log(`Using cached messages for chat ${chatId}`);
        const storedMessagesStr = localStorage.getItem(`chat_${chatId}_messages`);
        if (storedMessagesStr) {
          setMessages(JSON.parse(storedMessagesStr));
        }
      }
    } catch (error) {
      console.error('Failed to sync messages:', error);
    }
  }, [syncedChats]);

  const updateChatPreview = useCallback((message: Message) => {
    setChats(prevChats =>
        prevChats.map(chat =>
            chat.chatId === message.chatId
                ? {
                  ...chat,
                  lastMessageContent: message.message,
                  lastMessageSender: message.sender,
                  lastMessageSentDate: message.timestamp
                }
                : chat
        )
    );
  }, []);

  useEffect(() => {
    const unsubscribe = subscribeToMessages((message: Message) => {
      if (message.chatId === selectedChatId) {
        setMessages(prev => {
          const updated = [...prev, message];
          localStorage.setItem(`chat_${selectedChatId}_messages`, JSON.stringify(updated));
          return updated;
        });
      }
      updateChatPreview(message);
    });

    return () => unsubscribe();
  }, [selectedChatId, updateChatPreview, subscribeToMessages]);

  useEffect(() => {
    const storedChats = localStorage.getItem('my_chats');
    if (storedChats) {
      setChats(JSON.parse(storedChats).content);
    }
    loadChats();
  }, [loadChats]);

  useEffect(() => {
    if (selectedChatId) {
      loadMessages(selectedChatId);
    }
  }, [selectedChatId, loadMessages]);

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages]);

  const handleSendMessage = async () => {
    if (!selectedChatId || !newMessage.trim()) return;

    try {
      sendMessage(selectedChatId, newMessage);
      setNewMessage('');
    } catch (error) {
      console.error('Failed to send message:', error);
    }
  };

  const handleStartChat = async (username: string) => {
    try {
      const chatId = await chatService.startChat(username);
      setSelectedChatId(chatId);
      await loadChats();
    } catch (error) {
      console.error('Failed to start chat:', error);
    }
  };

  return (
      <ChatContainer>
        <Sidebar>
          <NewChat onStartChat={handleStartChat} />
          <ChatList>
            {chats.map(chat => (
                <ChatItem
                    key={chat.chatId}
                    active={chat.chatId === selectedChatId}
                    onClick={() => setSelectedChatId(chat.chatId)}
                >
                  <h4>{chat.receiverUsername}</h4>
                  <p>{chat.lastMessageContent}</p>
                  <small>
                    {new Date(chat.lastMessageSentDate).toLocaleTimeString()}
                  </small>
                </ChatItem>
            ))}
          </ChatList>
        </Sidebar>

        <ChatWindow>
          {selectedChatId ? (
              <>
                <MessageList>
                  {messages
                      .filter(msg => msg.chatId === selectedChatId)
                      .sort((a, b) => new Date(a.timestamp).getTime() - new Date(b.timestamp).getTime())
                      .map((msg, index) => (
                          <MessageBubble
                              key={index}
                              isMine={msg.sender === user?.username}
                          >
                            {msg.message}
                          </MessageBubble>
                      ))}
                  <div ref={messagesEndRef} />
                </MessageList>
                <InputArea>
                  <Input
                      value={newMessage}
                      onChange={(e) => setNewMessage(e.target.value)}
                      onKeyPress={(e) => e.key === 'Enter' && handleSendMessage()}
                      placeholder="Type a message..."
                  />
                  <SendButton onClick={handleSendMessage}>Send</SendButton>
                </InputArea>
              </>
          ) : (
              <div style={{ padding: 20, textAlign: 'center' }}>
                Select a chat to start messaging
              </div>
          )}
        </ChatWindow>
      </ChatContainer>
  );
};

export default Chat;
