// src/components/ChatWindow.vue
<script setup lang="ts">
import { ref, watch, nextTick, computed } from 'vue'
import type { Message } from '../services/chatService'
import { useAuthStore } from '../stores/auth'

interface Props {
  selectedChatId: number | null
  messages: Message[]
  receiverUsername?: string
}

const props = defineProps<Props>()
const emit = defineEmits<{
  sendMessage: [chatId: number, message: string]
  back: []
}>()

const authStore = useAuthStore()
const newMessage = ref('')
const messagesEndRef = ref<HTMLElement | null>(null)

const filteredMessages = computed(() => {
  if (!props.selectedChatId) return []
  return props.messages
    .filter(msg => msg.chatId === props.selectedChatId)
    .sort((a, b) => new Date(a.timestamp).getTime() - new Date(b.timestamp).getTime())
})

watch(() => props.messages, async () => {
  await nextTick()
  messagesEndRef.value?.scrollIntoView({ behavior: 'smooth' })
})

const handleSendMessage = async () => {
  if (!props.selectedChatId || !newMessage.value.trim()) return

  try {
    emit('sendMessage', props.selectedChatId, newMessage.value)
    newMessage.value = ''
  } catch (error) {
    console.error('Failed to send message:', error)
  }
}

const handleKeyPress = (e: KeyboardEvent) => {
  if (e.key === 'Enter') {
    handleSendMessage()
  }
}
</script>

<template>
  <div class="chat-window">
    <div v-if="selectedChatId && receiverUsername" class="header">
      <button class="back-button" @click="emit('back')">←</button>
      <h3 class="username">{{ receiverUsername }}</h3>
    </div>
    
    <template v-if="selectedChatId">
      <div class="message-list">
        <div
          v-for="(msg, index) in filteredMessages"
          :key="index"
          :class="['message-bubble', { mine: msg.sender === authStore.user?.username }]"
        >
          {{ msg.message }}
        </div>
        <div ref="messagesEndRef" />
      </div>
      <div class="input-area">
        <input
          v-model="newMessage"
          class="input"
          placeholder="Digite uma mensagem..."
          @keypress="handleKeyPress"
        />
        <button class="send-button" @click="handleSendMessage">
          Enviar
        </button>
      </div>
    </template>
    
    <div v-else class="placeholder">
      Selecione um chat para começar a conversar
    </div>
  </div>
</template>

<style scoped>
.chat-window {
  flex: 1;
  display: flex;
  flex-direction: column;
  background: #fff;
  height: 100%;
  overflow: hidden;
}

.header {
  display: flex;
  align-items: center;
  padding: 16px;
  background: #fff;
  border-bottom: 1px solid var(--color-border);
  flex-shrink: 0;
}

.back-button {
  background: none;
  border: none;
  font-size: 18px;
  cursor: pointer;
  margin-right: 10px;
}

.username {
  flex: 1;
  text-align: center;
  margin: 0;
}

.message-list {
  flex: 1;
  overflow-y: auto;
  padding: 20px;
  display: flex;
  flex-direction: column;
  gap: 10px;
  min-height: 0;
}

.input-area {
  display: flex;
  padding: 16px;
  background: var(--color-background-elevated);
  border-top: 1px solid var(--color-border);
  flex-shrink: 0;
}

.input {
  flex: 1;
  padding: 8px;
  margin-bottom: 0 !important;
  border: 1px solid #ddd;
  border-radius: 4px;
  font-family: inherit;
}

.send-button {
  margin-left: 10px;
  padding: 8px 16px;
  background: #007bff;
  color: #fff;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}

.placeholder {
  flex: 1;
  display: flex;
  align-items: center;
  justify-content: center;
  color: #888;
}

.message-bubble {
  max-width: 60%;
  padding: 6px 7px 8px 9px;
  background: #f1f1f1;
  color: #000;
  border-radius: 8px;
  align-self: flex-start;
}

.message-bubble.mine {
  background: #007bff;
  color: #fff;
  align-self: flex-end;
}
</style>

// src/components/chatWindow.tsx
import React, { useEffect, useRef, useState } from 'react';
import styled from 'styled-components';
import { Message } from '@/services/chatService';
import { useAuth } from '@/context/AuthContext';

const ChatWindow = styled.div`
    flex: 1;
    display: flex;
    flex-direction: column;
    background: #fff;
    height: 100%;
    overflow: hidden;
`;

const Header = styled.div`
    display: flex;
    align-items: center;
    padding: 16px;
    background: #fff;
    border-bottom: 1px solid ${props => props.theme.colors.border};
    flex-shrink: 0;
`;

const BackButton = styled.button`
    background: none;
    border: none;
    font-size: 18px;
    cursor: pointer;
    margin-right: 10px;
`;

const Username = styled.h3`
    flex: 1;
    text-align: center;
    margin: 0;
`;

const MessageList = styled.div`
    flex: 1;
    overflow-y: auto;
    padding: 20px;
    display: flex;
    flex-direction: column;
    gap: 10px;
    min-height: 0;
`;

const InputArea = styled.div`
    display: flex;
    padding: 16px;
    background: ${props => props.theme.colors.backgroundElevated};
    border-top: 1px solid ${props => props.theme.colors.border};
    flex-shrink: 0;
`;

const Input = styled.input`
    flex: 1;
    padding: 8px;
    margin-bottom: 0 !important;
    border: 1px solid #ddd;
    border-radius: 4px;
`;

const SendButton = styled.button`
    margin-left: 10px;
    padding: 8px 16px;
    background: #007bff;
    color: #fff;
    border: none;
    border-radius: 4px;
    cursor: pointer;
`;

const Placeholder = styled.div`
    flex: 1;
    display: flex;
    align-items: center;
    justify-content: center;
    color: #888;
`;

const MessageBubble = styled.div<{ isMine: boolean }>`
    max-width: 60%;
    padding: 6px 7px 8px 9px;
    background: ${props => (props.isMine ? '#007bff' : '#f1f1f1')};
    color: ${props => (props.isMine ? '#fff' : '#000')};
    border-radius: 8px;
    align-self: ${props => (props.isMine ? 'flex-end' : 'flex-start')};
`;

interface ChatWindowComponentProps {
    selectedChatId: number | null;
    messages: Message[];
    setMessages: React.Dispatch<React.SetStateAction<Message[]>>;
    sendMessage: (chatId: number, message: string) => void;
    onBack?: () => void;
    receiverUsername?: string;
}

const ChatWindowComponent: React.FC<ChatWindowComponentProps> = ({
    selectedChatId,
    messages,
    setMessages,
    sendMessage,
    onBack,
    receiverUsername,
}) => {
    const { user } = useAuth();
    const [newMessage, setNewMessage] = useState('');
    const messagesEndRef = useRef<HTMLDivElement>(null);

    useEffect(() => {
        messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
    }, [messages]);

    const handleSendMessage = async () => {
        if (!selectedChatId || !newMessage.trim()) return;

        try {
            sendMessage(selectedChatId, newMessage);
            setNewMessage('');
        } catch (error) {
            console.error('Failed to send message:', error);
        }
    };

    return (
        <ChatWindow>
            {selectedChatId && receiverUsername && (
                <Header>
                    <BackButton onClick={onBack}>←</BackButton>
                    <Username>{receiverUsername}</Username>
                </Header>
            )}
            {selectedChatId ? (
                <>
                    <MessageList>
                        {messages
                            .filter(msg => msg.chatId === selectedChatId)
                            .sort((a, b) => new Date(a.timestamp).getTime() - new Date(b.timestamp).getTime())
                            .map((msg, index) => (
                                <MessageBubble
                                    key={index}
                                    isMine={msg.sender === user?.username}
                                >
                                    {msg.message}
                                </MessageBubble>
                            ))}
                        <div ref={messagesEndRef} />
                    </MessageList>
                    <InputArea>
                        <Input
                            value={newMessage}
                            onChange={(e) => setNewMessage(e.target.value)}
                            onKeyPress={(e) => e.key === 'Enter' && handleSendMessage()}
                            placeholder="Digite uma mensagem..."
                        />
                        <SendButton onClick={handleSendMessage}>Enviar</SendButton>
                    </InputArea>
                </>
            ) : (
                <Placeholder>Selecione um chat para começar a conversar</Placeholder>
            )}
        </ChatWindow>
    );
};

export default ChatWindowComponent;
