// src/components/editImageModal.tsx
import React, { useEffect, useState } from 'react';
import styled from 'styled-components';
import ReactCrop, { Crop } from 'react-image-crop';
import 'react-image-crop/dist/ReactCrop.css';

interface EditImageModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSubmit: (file: File) => Promise<void>;
  type: 'profile' | 'header';
  currentImage?: string;
}

interface PreviewContainerProps {
  type: 'profile' | 'header';
}

export const EditImageModal = ({
  isOpen,
  onClose,
  onSubmit,
  type,
  currentImage
}: EditImageModalProps) => {
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [preview, setPreview] = useState<string>();
  const [crop, setCrop] = useState<Crop>({
    unit: '%',
    width: 100,
    height: type === 'profile' ? 100 : 33.33,
    x: 0,
    y: 0
  });

  useEffect(() => {
    if (!isOpen) {
      setPreview(undefined);
    }
  }, [isOpen, type]);

  const handleClose = () => {
    setPreview(undefined);
    onClose();
  };

  const handleImageChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files?.[0]) {
      const file = e.target.files[0];
      const reader = new FileReader();

      reader.onloadend = () => {
        setPreview(reader.result as string);
        setCrop({
          unit: '%',
          width: 100,
          height: type === 'profile' ? 100 : 33.33,
          x: 0,
          y: 0,
        });
      };

      reader.readAsDataURL(file);
    }
  };

  const getCroppedImg = async (imageSrc: string, crop: Crop): Promise<File> => {
    const image = await createImage(imageSrc);
    const canvas = document.createElement('canvas');
    const scaleX = image.naturalWidth / image.width;
    const scaleY = image.naturalHeight / image.height;

    canvas.width = crop.width as number;
    canvas.height = crop.height as number;

    const ctx = canvas.getContext('2d');
    if (!ctx) throw new Error('No 2d context');

    ctx.drawImage(
      image,
      (crop.x as number) * scaleX,
      (crop.y as number) * scaleY,
      (crop.width as number) * scaleX,
      (crop.height as number) * scaleY,
      0,
      0,
      canvas.width,
      canvas.height
    );

    return new Promise((resolve) => {
      canvas.toBlob((blob) => {
        if (blob) {
          resolve(new File([blob], 'cropped-image.jpg', { type: 'image/jpeg' }));
        }
      }, 'image/jpeg', 1.0);
    });
  };

  const handleSubmit = async () => {
    try {
      setIsSubmitting(true);
      if (preview) {
        const croppedImage = await getCroppedImg(preview, crop);
        await onSubmit(croppedImage);
        onClose();
      }
    } catch (error) {
      console.error('Error updating image:', error);
    } finally {
      setIsSubmitting(false);
    }
  };

  const createImage = (url: string): Promise<HTMLImageElement> =>
    new Promise((resolve, reject) => {
      const image = new Image();
      image.addEventListener('load', () => resolve(image));
      image.addEventListener('error', reject);
      image.src = url;
    });

  if (!isOpen) return null;

  return (
    <Overlay>
      <ModalContainer>
        <Header>
          <Title>Editar {type === 'profile' ? 'Foto de Perfil' : 'Capa'}</Title>
          <CloseButton onClick={handleClose}>✕</CloseButton>
        </Header>

        <Form>
          <ImageInput
            type="file"
            onChange={handleImageChange}
            accept="image/*"
            id="image-input"
          />
          <ImageLabel htmlFor="image-input">
            Escolher imagem
          </ImageLabel>

          {preview && (
            <PreviewContainer type={type}>
              <ReactCrop
                crop={crop}
                onChange={newCrop => setCrop(newCrop)}
                aspect={type === 'profile' ? 1 : 3}
              >
                <PreviewImage src={preview} alt="Preview" />
              </ReactCrop>
            </PreviewContainer>
          )}
        </Form>
        <ButtonGroup>
          <CancelButton onClick={handleClose}>Cancelar</CancelButton>
          <SaveButton onClick={handleSubmit}>Salvar</SaveButton>
        </ButtonGroup>
      </ModalContainer>
    </Overlay>
  );
};

const Overlay = styled.div`
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background-color: rgba(0, 0, 0, 0.7);
  display: flex;
  justify-content: center;
  align-items: center;
  z-index: 1000;
`;

const ModalContainer = styled.div`
  background-color: ${({ theme }) => theme.colors.backgroundAlt};
  border: 1px solid ${({ theme }) => theme.colors.border};
  border-radius: 12px;
  width: 90vw;
  max-width: 450px;
  padding: 20px;
  display: flex;
  flex-direction: column;
  gap: 16px;
  box-shadow: 0 4px 6px rgba(0, 0, 0, 0.2);
  overflow: hidden;
  max-height: 90vh;
  overflow-y: auto;

  @media (max-width: 768px) {
    width: 95vw;
    padding: 16px;
    max-height: 80vh;
  }

  @media (min-width: 1024px) {
    width: 40vw;
    max-width: 600px;
  }
`;

const Header = styled.div`
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding-bottom: 16px;
  border-bottom: 1px solid ${({ theme }) => theme.colors.border};
`;

const Title = styled.h2`
  color: ${({ theme }) => theme.colors.text};
  font-size: ${({ theme }) => theme.fontSizes.large};
  margin: 0;
`;

const CloseButton = styled.button`
  background: none;
  border: none;
  color: ${({ theme }) => theme.colors.text};
  font-size: ${({ theme }) => theme.fontSizes.large};
  cursor: pointer;
  padding: 4px;
  
  &:hover {
    color: ${({ theme }) => theme.colors.primary};
  }
`;

const Form = styled.div`
  display: flex;
  flex-direction: column;
  gap: 12px;
`;

const ImageInput = styled.input`
  display: none;
`;

const ImageLabel = styled.label`
  background-color: ${({ theme }) => theme.colors.primary};
  color: white;
  padding: 12px 20px;
  border-radius: 8px;
  cursor: pointer;
  text-align: center;
  font-weight: bold;
  transition: background-color 0.2s;

  &:hover {
    background-color: ${({ theme }) => theme.colors.secondary};
  }
`;

const PreviewContainer = styled.div<PreviewContainerProps>`
  position: relative;
  display: flex;
  justify-content: center;
  align-items: center;
  width: 100%;
  max-height: ${({ type }) => (type === 'profile' ? '40vh' : '30vh')};
  aspect-ratio: ${({ type }) => (type === 'profile' ? '1 / 1' : '3 / 1')};
  overflow: hidden;
  border-radius: 8px;

  @media (max-width: 768px) {
    max-height: ${({ type }) => (type === 'profile' ? '30vh' : '20vh')};
  }
`;

const PreviewImage = styled.img`
  display: block;
  max-width: 100%;
  max-height: 100%;
  width: auto;
  height: auto;
  object-fit: contain;
  object-position: center;
`;
const ButtonGroup = styled.div`
  display: flex;
  justify-content: flex-end;
  gap: 12px;
  margin-top: 20px;
`;

const Button = styled.button`
  padding: 10px 20px;
  border-radius: 8px;
  font-weight: bold;
  cursor: pointer;
  transition: all 0.2s;
`;

const CancelButton = styled(Button)`
  background: none;
  border: 1px solid ${({ theme }) => theme.colors.border};
  color: ${({ theme }) => theme.colors.text};

  &:hover {
    background-color: ${({ theme }) => theme.colors.backgroundElevated};
  }
`;

const SaveButton = styled(Button) <{ $isLoading?: boolean }>`
  background-color: ${({ theme, $isLoading }) =>
    $isLoading ? theme.colors.secondary : theme.colors.primary};
  border: none;
  color: white;
  pointer-events: ${props => props.$isLoading ? 'none' : 'auto'};
  opacity: ${props => props.$isLoading ? 0.7 : 1};

  &:hover {
    background-color: ${({ theme }) => theme.colors.secondary};
  }
`;

// src/components/EditImageModal.vue
<script setup lang="ts">
import { ref, watch } from 'vue'

interface Props {
  isOpen: boolean
  type: 'profile' | 'header'
  currentImage?: string
}

const props = defineProps<Props>()
const emit = defineEmits<{
  close: []
  submit: [file: File]
}>()

const imagePreview = ref<string | null>(null)
const selectedFile = ref<File | null>(null)
const isSubmitting = ref(false)
const fileInputRef = ref<HTMLInputElement | null>(null)

watch(() => props.isOpen, (newVal) => {
  if (!newVal) {
    imagePreview.value = null
    selectedFile.value = null
  }
})

const handleFileSelect = (event: Event) => {
  const target = event.target as HTMLInputElement
  const file = target.files?.[0]
  
  if (!file) return
  
  selectedFile.value = file
  
  const reader = new FileReader()
  reader.onload = () => {
    imagePreview.value = reader.result as string
  }
  reader.readAsDataURL(file)
}

const handleDrop = (event: DragEvent) => {
  event.preventDefault()
  const file = event.dataTransfer?.files[0]
  
  if (!file || !file.type.startsWith('image/')) return
  
  selectedFile.value = file
  
  const reader = new FileReader()
  reader.onload = () => {
    imagePreview.value = reader.result as string
  }
  reader.readAsDataURL(file)
}

const handleDragOver = (event: DragEvent) => {
  event.preventDefault()
}

const triggerFileSelect = () => {
  fileInputRef.value?.click()
}

const handleSubmit = async () => {
  if (!selectedFile.value || isSubmitting.value) return
  
  isSubmitting.value = true
  try {
    emit('submit', selectedFile.value)
    emit('close')
  } catch (error) {
    console.error('Error uploading image:', error)
  } finally {
    isSubmitting.value = false
  }
}
</script>

<template>
  <div v-if="isOpen" class="overlay" @click="emit('close')">
    <div class="modal-container" @click.stop>
      <div class="header">
        <h2 class="title">
          {{ type === 'profile' ? 'Editar Foto de Perfil' : 'Editar Foto de Capa' }}
        </h2>
        <button class="close-button" @click="emit('close')">✕</button>
      </div>

      <div class="content">
        <input
          ref="fileInputRef"
          type="file"
          accept="image/*"
          style="display: none"
          @change="handleFileSelect"
        />
        
        <div
          v-if="!imagePreview"
          class="dropzone"
          @drop="handleDrop"
          @dragover="handleDragOver"
          @click="triggerFileSelect"
        >
          <p>Arraste uma imagem aqui ou clique para selecionar</p>
        </div>
        
        <div v-else class="preview-container">
          <img
            :src="imagePreview"
            alt="Preview"
            :class="['preview-image', type === 'profile' ? 'profile' : 'header']"
          />
          <button class="change-button" @click="triggerFileSelect">
            Trocar Imagem
          </button>
        </div>

        <div class="button-group">
          <button class="cancel-button" @click="emit('close')" :disabled="isSubmitting">
            Cancelar
          </button>
          <button
            class="save-button"
            :disabled="!selectedFile || isSubmitting"
            @click="handleSubmit"
          >
            {{ isSubmitting ? 'Salvando...' : 'Salvar' }}
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped>
.overlay {
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background-color: rgba(0, 0, 0, 0.7);
  display: flex;
  justify-content: center;
  align-items: center;
  z-index: 1000;
}

.modal-container {
  background-color: var(--color-background-alt);
  border: 1px solid var(--color-border);
  border-radius: 12px;
  width: 600px;
  max-width: 90vw;
  padding: 20px;
  box-shadow: 0 4px 6px rgba(0, 0, 0, 0.2);
}

.header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding-bottom: 16px;
  border-bottom: 1px solid var(--color-border);
  margin-bottom: 20px;
}

.title {
  color: var(--color-text);
  font-size: var(--font-size-large);
  margin: 0;
}

.close-button {
  background: none;
  border: none;
  color: var(--color-text);
  font-size: 20px;
  cursor: pointer;
  padding: 0;
  width: 30px;
  height: 30px;
  display: flex;
  align-items: center;
  justify-content: center;
}

.close-button:hover {
  opacity: 0.7;
}

.content {
  display: flex;
  flex-direction: column;
  gap: 20px;
}

.dropzone {
  border: 2px dashed var(--color-border);
  border-radius: 8px;
  padding: 60px 20px;
  text-align: center;
  cursor: pointer;
  transition: all 0.2s;
  color: var(--color-text-light);
}

.dropzone:hover {
  border-color: var(--color-primary);
  background-color: var(--color-background-elevated);
}

.preview-container {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 16px;
}

.preview-image {
  max-width: 100%;
  border-radius: 8px;
  object-fit: cover;
}

.preview-image.profile {
  width: 200px;
  height: 200px;
  border-radius: 50%;
}

.preview-image.header {
  width: 100%;
  max-height: 200px;
}

.change-button {
  padding: 8px 16px;
  background-color: var(--color-background-elevated);
  border: 1px solid var(--color-border);
  border-radius: 8px;
  color: var(--color-text);
  cursor: pointer;
  transition: all 0.2s;
}

.change-button:hover {
  background-color: var(--color-background);
}

.button-group {
  display: flex;
  justify-content: flex-end;
  gap: 12px;
  padding-top: 16px;
  border-top: 1px solid var(--color-border);
}

.cancel-button,
.save-button {
  padding: 10px 20px;
  border-radius: 8px;
  font-size: var(--font-size-regular);
  font-weight: bold;
  cursor: pointer;
  transition: all 0.2s;
}

.cancel-button {
  background-color: transparent;
  border: 1px solid var(--color-border);
  color: var(--color-text);
}

.cancel-button:hover:not(:disabled) {
  background-color: var(--color-background-elevated);
}

.save-button {
  background-color: var(--color-primary);
  border: none;
  color: white;
}

.save-button:hover:not(:disabled) {
  background-color: var(--color-button-hover);
}

.save-button:disabled,
.cancel-button:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}
</style>
