// src/components/EditProfileModal.vue
<script setup lang="ts">
import { ref, watch } from 'vue'
import type { UpdatedUser } from '../models/UserProfile'

interface Props {
  isOpen: boolean
  currentDisplayName: string
  currentBio: string
}

const props = defineProps<Props>()
const emit = defineEmits<{
  close: []
  submit: [data: UpdatedUser]
}>()

const displayName = ref(props.currentDisplayName)
const bio = ref(props.currentBio)

watch(() => props.currentDisplayName, (newVal) => {
  displayName.value = newVal
})

watch(() => props.currentBio, (newVal) => {
  bio.value = newVal
})

const handleSubmit = async () => {
  try {
    emit('submit', { displayName: displayName.value, bio: bio.value })
    emit('close')
  } catch (error) {
    console.error('Error updating profile:', error)
  }
}
</script>

<template>
  <div v-if="isOpen" class="overlay" @click="emit('close')">
    <div class="modal-container" @click.stop>
      <div class="header">
        <h2 class="title">Editar Perfil</h2>
        <button class="close-button" @click="emit('close')">✕</button>
      </div>

      <form class="form" @submit.prevent="handleSubmit">
        <div class="input-group">
          <label class="label">Bio</label>
          <textarea
            v-model="bio"
            class="text-area"
            placeholder="Sua biografia"
          />
        </div>

        <div class="button-group">
          <button type="button" class="cancel-button" @click="emit('close')">
            Cancelar
          </button>
          <button type="submit" class="save-button">
            Salvar
          </button>
        </div>
      </form>
    </div>
  </div>
</template>

<style scoped>
.overlay {
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background-color: rgba(0, 0, 0, 0.7);
  display: flex;
  justify-content: center;
  align-items: center;
  z-index: 1000;
}

.modal-container {
  background-color: var(--color-background-alt);
  border: 1px solid var(--color-border);
  border-radius: 12px;
  width: 500px;
  max-width: 90vw;
  padding: 20px;
  box-shadow: 0 4px 6px rgba(0, 0, 0, 0.2);
}

.header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding-bottom: 16px;
  border-bottom: 1px solid var(--color-border);
}

.title {
  color: var(--color-text);
  font-size: var(--font-size-large);
  margin: 0;
}

.close-button {
  background: none;
  border: none;
  color: var(--color-text);
  font-size: 20px;
  cursor: pointer;
  padding: 0;
  width: 30px;
  height: 30px;
  display: flex;
  align-items: center;
  justify-content: center;
}

.close-button:hover {
  opacity: 0.7;
}

.form {
  padding-top: 20px;
}

.input-group {
  margin-bottom: 20px;
}

.label {
  display: block;
  color: var(--color-text);
  font-size: var(--font-size-regular);
  margin-bottom: 8px;
  font-weight: bold;
}

.text-area {
  width: 100%;
  min-height: 100px;
  padding: 12px;
  border: 1px solid var(--color-border);
  border-radius: 8px;
  background-color: var(--color-background);
  color: var(--color-text);
  font-size: var(--font-size-regular);
  resize: vertical;
  font-family: inherit;
}

.text-area:focus {
  outline: none;
  border-color: var(--color-primary);
}

.button-group {
  display: flex;
  justify-content: flex-end;
  gap: 12px;
}

.cancel-button,
.save-button {
  padding: 10px 20px;
  border-radius: 8px;
  font-size: var(--font-size-regular);
  font-weight: bold;
  cursor: pointer;
  transition: all 0.2s;
}

.cancel-button {
  background-color: transparent;
  border: 1px solid var(--color-border);
  color: var(--color-text);
}

.cancel-button:hover {
  background-color: var(--color-background-elevated);
}

.save-button {
  background-color: var(--color-primary);
  border: none;
  color: white;
}

.save-button:hover {
  background-color: var(--color-button-hover);
}
</style>

// src/components/editProfileModal.tsx
import React, { useState } from 'react';
import styled from 'styled-components';
import { UpdatedUser } from '@/models/UserProfile';

interface EditProfileModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSubmit: (data: UpdatedUser) => void;
  currentDisplayName: string;
  currentBio: string;
}

export const EditProfileModal = ({
  isOpen,
  onClose,
  onSubmit,
  currentDisplayName,
  currentBio,
}: EditProfileModalProps) => {
  const [displayName, setDisplayName] = useState(currentDisplayName);
  const [bio, setBio] = useState(currentBio);

  const handleSubmit = async () => {
    try {
      await onSubmit({ displayName, bio });
      onClose();
    } catch (error) {
      console.error('Error updating profile:', error);
    }
  };

  if (!isOpen) return null;

  return (
    <Overlay>
      <ModalContainer>
        <Header>
          <Title>Editar Perfil</Title>
          <CloseButton onClick={onClose}>✕</CloseButton>
        </Header>

        <Form>
          {/* <InputGroup>
            <Label>Nome</Label>
            <Input 
              value={displayName}
              onChange={(e) => setDisplayName(e.target.value)}
              placeholder="Seu nome"
            />
          </InputGroup> */}

          <InputGroup>
            <Label>Bio</Label>
            <TextArea 
              value={bio}
              onChange={(e) => setBio(e.target.value)}
              placeholder="Sua biografia"
            />
          </InputGroup>

          <ButtonGroup>
            <CancelButton onClick={onClose}>Cancelar</CancelButton>
            <SaveButton onClick={handleSubmit}>Salvar</SaveButton>
          </ButtonGroup>
        </Form>
      </ModalContainer>
    </Overlay>
  );
};

const Overlay = styled.div`
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background-color: rgba(0, 0, 0, 0.7);
  display: flex;
  justify-content: center;
  align-items: center;
  z-index: 1000;
`;

const ModalContainer = styled.div`
  background-color: ${({ theme }) => theme.colors.backgroundAlt};
  border: 1px solid ${({ theme }) => theme.colors.border};
  border-radius: 12px;
  width: 500px;
  padding: 20px;
  box-shadow: 0 4px 6px rgba(0, 0, 0, 0.2);
`;

const Header = styled.div`
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding-bottom: 16px;
  border-bottom: 1px solid ${({ theme }) => theme.colors.border};
`;

const Title = styled.h2`
  color: ${({ theme }) => theme.colors.text};
  font-size: ${({ theme }) => theme.fontSizes.large};
  margin: 0;
`;

const CloseButton = styled.button`
  background: none;
  border: none;
  color: ${({ theme }) => theme.colors.text};
  font-size: ${({ theme }) => theme.fontSizes.large};
  cursor: pointer;
  padding: 4px;
  
  &:hover {
    color: ${({ theme }) => theme.colors.primary};
  }
`;

const Form = styled.div`
  margin-top: 20px;
  display: flex;
  flex-direction: column;
  gap: 16px;
`;

const ButtonGroup = styled.div`
  display: flex;
  justify-content: flex-end;
  gap: 12px;
  margin-top: 20px;
`;

const Button = styled.button`
  padding: 10px 20px;
  border-radius: 8px;
  font-weight: bold;
  cursor: pointer;
  transition: all 0.2s;
`;

const CancelButton = styled(Button)`
  background: none;
  border: 1px solid ${({ theme }) => theme.colors.border};
  color: ${({ theme }) => theme.colors.text};

  &:hover {
    background-color: ${({ theme }) => theme.colors.backgroundElevated};
  }
`;

const SaveButton = styled(Button)`
  background-color: ${({ theme }) => theme.colors.primary};
  border: none;
  color: white;

  &:hover {
    background-color: ${({ theme }) => theme.colors.secondary};
  }
`;

const InputGroup = styled.div`
  display: flex;
  flex-direction: column;
  gap: 8px;
`;

const Label = styled.label`
  color: ${({ theme }) => theme.colors.text};
  font-size: ${({ theme }) => theme.fontSizes.medium};
  font-weight: bold;
`;

const Input = styled.input`
  padding: 10px;
  border: 1px solid ${({ theme }) => theme.colors.border};
  border-radius: 8px;
  background-color: ${({ theme }) => theme.colors.background};
  color: ${({ theme }) => theme.colors.text};
  font-size: ${({ theme }) => theme.fontSizes.medium};
  
  &:focus {
    border-color: ${({ theme }) => theme.colors.primary};
    outline: none;
    box-shadow: 0 0 0 2px ${({ theme }) => theme.colors.primary}33;
  }
`;

const TextArea = styled.textarea`
  padding: 10px;
  border: 1px solid ${({ theme }) => theme.colors.border};
  border-radius: 8px;
  background-color: ${({ theme }) => theme.colors.background};
  color: ${({ theme }) => theme.colors.text};
  font-size: ${({ theme }) => theme.fontSizes.medium};
  resize: vertical;
  
  &:focus {
    border-color: ${({ theme }) => theme.colors.primary};
    outline: none;
    box-shadow: 0 0 0 2px ${({ theme }) => theme.colors.primary}33;
  }
`;
