// src/components/layout.tsx
import React from 'react';
import styled from 'styled-components';
import { useRouter } from 'next/router';
import { useAuth } from '@/context/AuthContext';
import { getImageById } from '@/services/imageService';
import { useEffect, useState } from 'react';

interface ProfileImageProps {
    imageId: number | null | undefined;
    size?: 'small' | 'medium' | 'large';
    className?: string;
}

const Layout = ({ children }: { children: React.ReactNode }) => {
    const router = useRouter();
    const { isAuthenticated, user, logout, isLoading } = useAuth();
    const isAuthPage = router.pathname.startsWith('/auth');

    if (isAuthPage) {
        return <>{children}</>;
    }

    if (isLoading && !isAuthenticated) {
        return (
            <>
                <Header>
                    <LoadingState>Carregando...</LoadingState>
                </Header>
                <Main>{children}</Main>
            </>
        );
    }

    const handleProfileClick = () => {
        if (user?.username) {
            router.push(`/profile/${user.username}`);
        }
    };

    const ProfileImage = ({ imageId }: ProfileImageProps) => {
        const [imageUrl, setImageUrl] = useState<string>('');
        const [isLoading, setIsLoading] = useState(true);
        const { user } = useAuth();
    
        useEffect(() => {
            const loadImage = async () => {
                if (!user) return;
                
                setIsLoading(true);
                if (imageId) {
                    try {
                        const url = await getImageById(imageId);
                        setImageUrl(url);
                    } catch (error) {
                        console.error('Error loading profile image:', error);
                        setImageUrl('/default-profile.png');
                    }
                } else {
                    setImageUrl('/default-profile.png');
                }
                setIsLoading(false);
            };
    
            loadImage();
        }, [imageId, user]);
    
        if (isLoading) {
            return <LoadingProfileImage />;
        }
    
        return (
            <StyledProfileImage
                src={imageUrl}
                alt="Profile"
                onError={(e) => {
                    e.currentTarget.src = '/default-profile.png';
                }}
            />
        );
    };

    const renderHeaderContent = () => {
        return isAuthenticated ? (
            <>
                <ProfileButton onClick={handleProfileClick}>
                    <ProfileImage imageId={user?.profileImageId} />
                </ProfileButton>
                <AppName onClick={() => router.push('/')}>toiter</AppName>
                <LogoutButton onClick={() => logout()}>Logout</LogoutButton>
            </>
        ) : (
            <>
                <AppName onClick={() => router.push('/')}>toiter</AppName>
                <LoginButton onClick={() => router.push('/auth/login')}>
                    Login
                </LoginButton>
            </>
        );
    };

    return (
        <>
            <Header>
                {renderHeaderContent()}
            </Header>
            <Main>{children}</Main>
        </>
    );
};

export default Layout;

const LoadingState = styled.div`
    color: ${({ theme }) => theme.colors.text};
    font-size: ${({ theme }) => theme.fontSizes.regular};
`;

const Header = styled.div`
    background-color: ${({ theme }) => theme.colors.backgroundElevated};
    padding: 0 24px;
    width: 100%;
    display: flex;
    justify-content: space-between;
    align-items: center;
    border-bottom: 1px solid ${({ theme }) => theme.colors.border};
    position: sticky;
    top: 0;
    z-index: 10;
`;

const AppName = styled.h1`
    color: ${({ theme }) => theme.colors.primary};
    font-size: ${({ theme }) => theme.fontSizes.xlarge};
    font-weight: bold;
    cursor: pointer;
    transition: all 0.2s ease;
    padding-bottom: 2px;
    border-bottom: 2px solid transparent;

    &:hover {
        opacity: 0.8;
        border-bottom: 2px solid ${({ theme }) => theme.colors.primary};
    }
`;

const StyledProfileImage = styled.img`
    width: 40px;
    height: 40px;
    border-radius: 50%;
    object-fit: cover;
    border: 2px solid ${({ theme }) => theme.colors.primary};
`;

const ProfileButton = styled.button`
    background: none;
    border: none;
    padding: 0;
    cursor: pointer;
    display: flex;
    align-items: center;
    justify-content: center;
    transition: opacity 0.2s;

    &:hover {
        opacity: 0.8;
    }
`;

const LogoutButton = styled.button`
    background-color: ${({ theme }) => theme.colors.primary};
    color: ${({ theme }) => theme.colors.text};
    padding: 8px 16px;
    border: none;
    border-radius: 8px;
    font-size: ${({ theme }) => theme.fontSizes.regular};
    font-weight: bold;
    cursor: pointer;
    transition: all 0.2s ease;

    &:hover {
        background-color: ${({ theme }) => theme.colors.secondary};
        transform: translateY(-1px);
    }
`;

const Main = styled.main`
    
`;

const LoginButton = styled.button`
  background-color: ${({ theme }) => theme.colors.primary};
  color: ${({ theme }) => theme.colors.text};
  padding: 8px 16px;
  border: none;
  border-radius: 8px;
  font-size: ${({ theme }) => theme.fontSizes.regular};
  font-weight: bold;
  cursor: pointer;
  transition: all 0.2s ease;

  &:hover {
    background-color: ${({ theme }) => theme.colors.secondary};
    transform: translateY(-1px);
  }
`;

const LoadingProfileImage = styled.div`
    width: 40px;
    height: 40px;
    border-radius: 50%;
    border: 2px solid ${({ theme }) => theme.colors.primary};
    background: ${({ theme }) => theme.colors.backgroundAlt};
    animation: pulse 1.5s ease-in-out infinite;

    @keyframes pulse {
        0% {
            opacity: 1;
        }
        50% {
            opacity: 0.4;
        }
        100% {
            opacity: 1;
        }
    }
`;

// src/components/Layout.vue
<script setup lang="ts">
import { computed, ref, watch, onMounted } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { useAuthStore } from '../stores/auth'
import { getImageById } from '../services/imageService'

const route = useRoute()
const router = useRouter()
const authStore = useAuthStore()

const imageUrl = ref<string>('')
const imageLoading = ref(true)

const isAuthPage = computed(() => route.path.startsWith('/auth'))

const loadProfileImage = async () => {
  if (!authStore.user) return
  
  imageLoading.value = true
  if (authStore.user.profileImageId) {
    try {
      const url = await getImageById(authStore.user.profileImageId)
      imageUrl.value = url
    } catch (error) {
      console.error('Error loading profile image:', error)
      imageUrl.value = '/default-profile.png'
    }
  } else {
    imageUrl.value = '/default-profile.png'
  }
  imageLoading.value = false
}

const handleProfileClick = () => {
  if (authStore.user?.username) {
    router.push(`/profile/${authStore.user.username}`)
  }
}

const handleLogout = () => {
  authStore.logout()
}

const handleLogin = () => {
  router.push('/auth/login')
}

const handleHomeClick = () => {
  router.push('/')
}

watch(() => authStore.user, () => {
  if (authStore.user) {
    loadProfileImage()
  }
}, { immediate: true })

onMounted(() => {
  if (authStore.user) {
    loadProfileImage()
  }
})
</script>

<template>
  <div v-if="!isAuthPage">
    <header class="header">
      <button v-if="authStore.isAuthenticated" class="profile-button" @click="handleProfileClick">
        <div v-if="imageLoading" class="loading-profile-image" />
        <img 
          v-else
          :src="imageUrl"
          alt="Profile"
          class="profile-image"
          @error="imageUrl = '/default-profile.png'"
        />
      </button>
      <h1 class="app-name" @click="handleHomeClick">toiter</h1>
      <button v-if="authStore.isAuthenticated" class="logout-button" @click="handleLogout">
        Logout
      </button>
      <button v-else class="login-button" @click="handleLogin">
        Login
      </button>
    </header>
  </div>
  
  <main class="main">
    <div v-if="authStore.isLoading && !authStore.isAuthenticated" class="loading-state">
      Carregando...
    </div>
    <slot v-else />
  </main>
</template>

<style scoped>
.header {
  background-color: var(--color-background-elevated);
  padding: 0 24px;
  width: 100%;
  display: flex;
  justify-content: space-between;
  align-items: center;
  border-bottom: 1px solid var(--color-border);
  position: sticky;
  top: 0;
  z-index: 10;
}

.loading-state {
  color: var(--color-text);
  font-size: var(--font-size-regular);
  text-align: center;
  padding: 40px;
}

.app-name {
  color: var(--color-primary);
  font-size: var(--font-size-xlarge);
  font-weight: 700;
  cursor: pointer;
  transition: all 0.2s ease;
  padding-bottom: 2px;
  border-bottom: 2px solid transparent;
  margin: 16px 0;
}

.app-name:hover {
  opacity: 0.8;
  border-bottom: 2px solid var(--color-primary);
}

.profile-image {
  width: 40px;
  height: 40px;
  border-radius: 50%;
  object-fit: cover;
  border: 2px solid var(--color-primary);
}

.profile-button {
  background: none;
  border: none;
  padding: 0;
  cursor: pointer;
  display: flex;
  align-items: center;
  justify-content: center;
  transition: opacity 0.2s;
}

.profile-button:hover {
  opacity: 0.8;
}

.logout-button,
.login-button {
  background-color: var(--color-primary);
  color: var(--color-text);
  padding: 8px 16px;
  border: none;
  border-radius: 8px;
  font-size: var(--font-size-regular);
  font-weight: 600;
  cursor: pointer;
  transition: all 0.2s ease;
}

.logout-button:hover,
.login-button:hover {
  background-color: var(--color-secondary);
  transform: translateY(-1px);
}

.loading-profile-image {
  width: 40px;
  height: 40px;
  border-radius: 50%;
  border: 2px solid var(--color-primary);
  background: var(--color-background-alt);
  animation: pulse 1.5s ease-in-out infinite;
}

@keyframes pulse {
  0% {
    opacity: 1;
  }
  50% {
    opacity: 0.4;
  }
  100% {
    opacity: 1;
  }
}

.main {
  /* Add any main content styles if needed */
}
</style>
